services:
  db:
    container_name: postgre_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - test_net
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: db@postgre.com
      PGADMIN_DEFAULT_PASSWORD: postgre
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - test_net

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/data/postgre_db'

     
networks:
  test_net: {}